# Generated by Django 4.2.5 on 2023-11-02 03:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compass", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="class_type",
            field=models.CharField(
                choices=[
                    ("Seminar", "Seminar"),
                    ("Lecture", "Lecture"),
                    ("Precept", "Precept"),
                    ("Unknown", "Unknown"),
                    ("Class", "Class"),
                    ("Studio", "Studio"),
                    ("Drill", "Drill"),
                    ("Lab", "Lab"),
                    ("Ear training", "Ear training"),
                ],
                default="",
                max_length=50,
            ),
        ),
    ]
