# Generated by Django 4.2.5 on 2023-11-05 01:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compass", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="university_id",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
