# Generated by Django 4.2.5 on 2023-11-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('compass', '0002_alter_customuser_university_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='net_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='university_id',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(
                blank=True, default='', max_length=254, verbose_name='email address'
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(
                blank=True, default='', max_length=150, verbose_name='first name'
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(
                blank=True, default='', max_length=150, verbose_name='last name'
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
