# Generated by Django 4.2.5 on 2023-11-02 04:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compass", "0002_section_class_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academicterm",
            name="term_code",
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="minor",
            name="apply_by_semester",
            field=models.IntegerField(default=6),
        ),
    ]
