# Generated by Django 4.2.5 on 2023-11-02 06:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compass", "0003_alter_academicterm_term_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="class_section",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="section",
            name="status",
            field=models.CharField(max_length=1, null=True),
        ),
    ]
