# Generated by Django 4.2.6 on 2023-11-04 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0004_alter_certificate_urls_alter_degree_urls_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='dept_list',
            field=models.JSONField(null=True),
        ),
    ]
