DEPTS = {
    'AAS': 'African American Studies',
    'AFS': 'African Studies',
    'AMS': 'American Studies',
    'ANT': 'Anthropology',
    'AOS': 'Atmospheric & Oceanic Sciences',
    'APC': 'Applied and Computational Math',
    'ARA': 'Arabic',
    'ARC': 'Architecture',
    'ART': 'Art and Archaeology',
    'ASA': 'Asian American Studies',
    'AST': 'Astrophysical Sciences',
    'ATL': 'Atelier',
    'BCS': 'Bosnian-Croatian-Serbian',
    'CBE': 'Chemical and Biological Engr',
    'CEE': 'Civil and Environmental Engr',
    'CGS': 'Cognitive Science',
    'CHI': 'Chinese',
    'CHM': 'Chemistry',
    'CHV': 'Center for Human Values',
    'CLA': 'Classics',
    'CLG': 'Classical Greek',
    'COM': 'Comparative Literature',
    'COS': 'Computer Science',
    'CTL': 'Center for Teaching & Learning',
    'CWR': 'Creative Writing',
    'CZE': 'Czech',
    'DAN': 'Dance',
    'EAS': 'East Asian Studies',
    'ECE': 'Electrical and Computer Engineering',
    'ECO': 'Economics',
    'ECS': 'European Cultural Studies',
    'EEB': 'Ecology and Evol Biology',
    'EGR': 'Engineering',
    'ELE': 'Electrical Engineering',
    'ENE': 'Energy Studies',
    'ENG': 'English',
    'ENT': 'Entrepreneurship',
    'ENV': 'Environmental Studies',
    'EPS': 'Contemporary European Politics',
    'FIN': 'Finance',
    'FRE': 'French',
    'FRS': 'Freshman Seminars',
    'GEO': 'Geosciences',
    'GER': 'German',
    'GHP': 'Global Health & Health Policy',
    'GLS': 'Global Seminar',
    'GSS': 'Gender and Sexuality Studies',
    'HEB': 'Hebrew',
    'HIN': 'Hindi',
    'HIS': 'History',
    'HLS': 'Hellenic Studies',
    'HOS': 'History of Science',
    'HPD': 'History/Practice of Diplomacy',
    'HUM': 'Humanistic Studies',
    'ISC': 'Integrated Science Curriculum',
    'ITA': 'Italian',
    'JDS': 'Judaic Studies',
    'JPN': 'Japanese',
    'JRN': 'Journalism',
    'KOR': 'Korean',
    'LAO': 'Latino Studies',
    'LAS': 'Latin American Studies',
    'LAT': 'Latin',
    'LCA': 'Lewis Center for the Arts',
    'LIN': 'Linguistics',
    'MAE': 'Mech and Aerospace Engr',
    'MAT': 'Mathematics',
    'MED': 'Medieval Studies',
    'MOD': 'Media and Modernity',
    'MOG': 'Modern Greek',
    'MOL': 'Molecular Biology',
    'MPP': 'Music Performance',
    'MSE': 'Materials Science and Engr',
    'MTD': 'Music Theater',
    'MUS': 'Music',
    'NES': 'Near Eastern Studies',
    'NEU': 'Neuroscience',
    'ORF': 'Oper Res and Financial Engr',
    'PAW': 'Ancient World',
    'PER': 'Persian',
    'PHI': 'Philosophy',
    'PHY': 'Physics',
    'PLS': 'Polish',
    'POL': 'Politics',
    'POP': 'Population Studies',
    'POR': 'Portuguese',
    'PSY': 'Psychology',
    'QCB': 'Quantitative Computational Bio',
    'REL': 'Religion',
    'RES': 'Russian, East Europ, Eurasian',
    'RUS': 'Russian',
    'SAN': 'Sanskrit',
    'SAS': 'South Asian Studies',
    'SLA': 'Slavic Languages and Lit',
    'SML': 'Statistics & Machine Learning',
    'SOC': 'Sociology',
    'SPA': 'Spanish',
    'SPI': 'Public and International Affairs',
    'STC': 'Science and Technology Council',
    'SWA': 'Swahili',
    'THR': 'Theater',
    'TPP': 'Teacher Preparation',
    'TRA': 'Translation, Intercultural Com',
    'TUR': 'Turkish',
    'TWI': 'Twi',
    'URB': 'Urban Studies',
    'URD': 'Urdu',
    'VIS': 'Visual Arts',
    'WRI': 'Princeton Writing Program',
    'WWS': 'Public and International Affairs',
}

AB_MAJORS = {
    'AAS': 'African American Studies',
    'ANT': 'Anthropology',
    'ARC': 'Architecture',
    'ART': 'Art and Archaeology',
    'AST': 'Astrophysical Sciences',
    'CHM': 'Chemistry',
    'CLA': 'Classics',
    'COM': 'Comparative Literature',
    'COS-AB': 'Computer Science - A.B.',
    'EAS': 'East Asian Studies',
    'ECO': 'Economics',
    'EEB': 'Ecology and Evolutionary Biology',
    'ENG': 'English',
    'FIT': 'French and Italian',
    'GEO': 'Geosciences',
    'GER': 'German',
    'HIS': 'History',
    'MAT': 'Mathematics',
    'MOL': 'Molecular Biology',
    'MUS': 'Music',
    'NES': 'Near Eastern Studies',
    'NEU': 'Neuroscience',
    'PHI': 'Philosophy',
    'PHY': 'Physics',
    'POL': 'Politics',
    'PSY': 'Psychology',
    'REL': 'Religion',
    'SLA': 'Slavic Languages and Literatures',
    'SOC': 'Sociology',
    'SPO': 'Spanish and Portuguese',
    'SPI': 'Public and International Affairs',
}

BSE_MAJORS = {
    'CBE': 'Chemical and Biological Engineering',
    'CEE': 'Civil and Environmental Engineering',
    'COS-BSE': 'Computer Science - B.S.E.',
    'ECE': 'Electrical Engineering',
    'MAE': 'Mechanical and Aerospace Engineering',
    'ORF': 'Operations Research and Financial Engineering',
}
