name: Backend CI/CD

on:
  push:
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: pip install -r backend/requirements.txt

    - name: Run Migrations
      run: python backend/manage.py migrate

    # Run your tests here (if any)
    # - name: Run Tests
    #   run: python backend/manage.py test

